#!/usr/bin/env python

import sys, json, requests, logging, string, random
# logging.basicConfig(level=logging.DEBUG)
id = ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(8))
payload = json.load(sys.stdin)

try:
    token = payload['source']['token']
except:
    sys.exit(255)

API_URL = 'https://api.digitalocean.com'
HEADERS = { 'Authorization': "Bearer {token}".format(token=payload['source']['token']) }

get_clusters = "{api}/v2/kubernetes/clusters".format(api=API_URL)
r = requests.get(get_clusters, headers=HEADERS)

output = [
    { 'ref': id }
]

print(json.dumps(output))
