name: Build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: kdihalas/digitalocean-kubernetes-resource

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9 # v3.0.5
        with:
          cosign-release: 'v1.13.1'

      # Setup QEMU for cross compilation
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        
      # Setup buildx for building containers
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@2a81c53912fc7ca31856d300b1f878a8e43178dd

      # Login to Docker hub
      # https://github.com/docker/login-action
      - name: Log into registry Docker Hub
        uses: docker/login-action@360b4b5fefbd590a50c2ff0c234dbd9fa6b08759
        with:
          username: kdihalas
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@dbbf01822bb698575d92e1ee5b9229d58745b0c6
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}