name: Build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: kdihalas/digitalocean-kubernetes-resource

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@2dd22fa31c04297d369158eb483250f578504a9f

      - name: Log into registry Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@3da7dc6e2b31f99ef2cb9fb4c50fb0971e0d0139
        with:
          username: kdihalas
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@766400ca14a75010e7b2e3119aa0d5b46826e8c7
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@a3ae207c1434ab875aa11554ce639ff512f25e89
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm64/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max